version: '3'

services:
  app:
    build: .
    command: "sh -c 'npm install && npm run start:dev'"
    # container_name: desafio2-transaction-api-nest
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  # db:
  #   build: .docker/database.sqlite